deck:
    type: texas.card_constructor.CartesianConstructor
    kwargs:
        rank: ['A', 'K', 'Q', 'J', 'T', '9', '8', '7', '6']
        suit: ['h', 's', 'd', 'c']
    
card_sampler:
    dependence: [deck]
    type: texas.card_sampler.RandomCardSampler
    kwargs:
        
compairer:
    dependence: [deck]
    type: texas.card_compair.FiveCardDicTexasCompairer
    kwargs:
        dicfile: ../data/card5_dic_sorted_shortdeck.txt
    
rule:
    type: texas.rules_builder.FiveCardRulesBuilder
    kwargs:
        rule:
            rounds: 4
            rounds_cards:
                - 0
                - 3
                - 1
                - 1
            deal_card_number: 2
            players: 2
            raise_limit: 3
            check_limit: 2
            amounts:
                small_blind: 0.5
                big_blind: 1
                max_chip: 10
            stack: 100
            bet_sizes:
                - 0.5_pot
                - 1_pot
                - 2_pot
                - all-in
            actions:
                - begin
                - bet
                - check
                - call
                - raise
                - fold
            legal_actions_after:
                begin: 
                    - call
                    - raise
                    - fold
                roundbegin:
                    - check 
                    - bet 
                bet:
                    - call
                    - raise
                    - fold
                raise:
                    - call
                    - raise
                    - fold
                check:
                    - check
                    - raise
                    - bet
                fold:
                
                call:
                    - check
                    - raise
                
tree_builder:
    dependence: [rule]
    type: texas.tree_builder.FiveCardTexasTreeBuilder
    kwargs:
    
card_abstraction:
    dependence: [deck]
    type: texas.card_abstraction.MemoryAbstraction
    kwargs:
        preflop_file: ../data/abstractions/PHS1_PREFLOP.txt
        preflop_lines: 630
        flop_file: ../data/abstractions/PHS1_FLOP_300buckets.txt
        flop_lines: 3769920
        turn_file: ../data/abstractions/PHS1_TURN_300buckets.txt
        turn_lines: 29216880
        river_file: ../data/abstractions/PHS1_RIVER_300buckets.txt
        river_lines: 175301280
        
strategy_profile:
    type: texas.optimizers.optimizer_public_chance_cfr.StrategyProfile
    kwargs:
    
trainer:
    dependence: [deck,card_sampler,compairer,rule,tree_builder,card_abstraction,strategy_profile]
    type: texas.optimizers.optimizer_public_chance_cfr.PublicChanceCFR
    kwargs:
        iterations: 50000
        print_interval: 1000
        debug: False
        
        